### ISSUE TITLE
Posters list scrolling/sizing problems

### ISSUE THREAD

**Issue by harry-wood** [openstreetmap/stateofthemap-2022#7]
The poster list page https://2022.stateofthemap.org/posters  ...shows a list of links on the left and posters on the right, but the list is annoying for various reasons. Mostly because it's quite narrow and tall, so it also has to be scrolled a lot.

Ideally we'd avoid that double-scroll-area effect by dramatically condensing the vertical space it uses somehow. An extreme option would be just list numbers perhaps. I suppose another extreme suggestion would be to drop it altogether. After all, on mobile screen widths we go without it.
But maybe if it just scrolled a bit less it would be an improvement i.e. if the list was a bit more vertically compact. Make it wider and use a smaller not-bold font so it wraps less.

Another annoying thing is that the scroll animation is taking the page to point where the relevant heading is just off the top.

Also there's no list entry for the final poster on the page (or is it hidden off the bottom when scrolling down?)

**Comment by tyrasd** [comment]
The scrolling and missing poster are now fixed.

I've also tweaked the table of contents to be clipped to a single line, making it more compact. If that's still too much, we can also drop it, it's definitely not essential to keep it.

**Comment by harry-wood** [comment]
Yeah that's a good improvement I reckon. It won't really be very nice unless the double-scrolling is eliminated somehow, but it no longer feels like it is very wasteful with vertical space (like I'm scrolling for no good reason) 👍
